import { boolean, integer, pgTable, serial, text, timestamp } from "drizzle-orm/pg-core";

export const memoryGames = pgTable("memory_games", {
  id:               serial("id").primaryKey(),
  slug:             text("slug").notNull().unique(),
  betCrc:           integer("bet_crc").notNull(),
  difficulty:       text("difficulty").notNull().default("medium"),
  recipientAddress: text("recipient_address").notNull(),
  commissionPct:    integer("commission_pct").notNull().default(5),
  player1Address:   text("player1_address"),
  player2Address:   text("player2_address"),
  player1TxHash:    text("player1_tx_hash"),
  player2TxHash:    text("player2_tx_hash"),
  player1Token:     text("player1_token"),
  player2Token:     text("player2_token"),
  player1Moves:     integer("player1_moves"),
  player1Time:      integer("player1_time"),
  player2Moves:     integer("player2_moves"),
  player2Time:      integer("player2_time"),
  isPrivate:        boolean("is_private").notNull().default(false),
  rematchSlug:      text("rematch_slug"),
  gridSeed:         text("grid_seed").notNull(),
  currentTurn:      text("current_turn").notNull().default("player1"),
  player1Pairs:     integer("player1_pairs").notNull().default(0),
  player2Pairs:     integer("player2_pairs").notNull().default(0),
  boardState:       text("board_state").notNull().default("{}"),
  status:           text("status").notNull().default("waiting_p1"),
  winnerAddress:    text("winner_address"),
  result:           text("result"),
  payoutStatus:     text("payout_status").notNull().default("pending"),
  payoutTxHash:     text("payout_tx_hash"),
  createdAt:        timestamp("created_at").defaultNow().notNull(),
  updatedAt:        timestamp("updated_at").defaultNow().notNull(),
});
