-- 0000_initial_baseline.sql
--
-- Full baseline for NF Society's 51 tables. Regenerated by drizzle-kit
-- in PR #11 from the current schema/*.ts files.
--
-- Fully idempotent:
--   - CREATE TABLE IF NOT EXISTS on every table
--   - ALTER TABLE ADD CONSTRAINT wrapped in DO $$ EXCEPTION blocks, so
--     re-running on a DB that already has the FK is a no-op.
--
-- Previous migrations (0000-0011, pre-PR#11) are preserved under
-- drizzle/archive/ for historical reference only; they are not applied
-- by drizzle-kit migrate anymore.
--

CREATE TABLE IF NOT EXISTS "badges" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"icon" text NOT NULL,
	"icon_type" text DEFAULT 'emoji' NOT NULL,
	"category" text NOT NULL,
	"secret" boolean DEFAULT false NOT NULL,
	"condition" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "badges_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bot_state" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"last_nonce" integer NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "claimed_payments" (
	"id" serial PRIMARY KEY NOT NULL,
	"tx_hash" text NOT NULL,
	"game_type" text NOT NULL,
	"game_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"amount_crc" integer NOT NULL,
	"claimed_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "claimed_payments_tx_hash_unique" UNIQUE("tx_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "exchanges" (
	"id" serial PRIMARY KEY NOT NULL,
	"sender_address" text NOT NULL,
	"amount_crc" text NOT NULL,
	"amount_human" text NOT NULL,
	"incoming_tx_hash" text NOT NULL,
	"outgoing_tx_hash" text,
	"status" text DEFAULT 'detected' NOT NULL,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "exchanges_incoming_tx_hash_unique" UNIQUE("incoming_tx_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "feature_flags" (
	"key" text PRIMARY KEY NOT NULL,
	"status" text DEFAULT 'enabled' NOT NULL,
	"label" text NOT NULL,
	"category" text DEFAULT 'general' NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "nf_auth_tokens" (
	"id" serial PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"address" text,
	"tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL,
	CONSTRAINT "nf_auth_tokens_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "payouts" (
	"id" serial PRIMARY KEY NOT NULL,
	"game_type" text NOT NULL,
	"game_id" text NOT NULL,
	"recipient_address" text NOT NULL,
	"amount_crc" real NOT NULL,
	"reason" text,
	"wrap_tx_hash" text,
	"transfer_tx_hash" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "payouts_game_id_unique" UNIQUE("game_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "player_badges" (
	"id" serial PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"badge_slug" text NOT NULL,
	"earned_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "players" (
	"address" text PRIMARY KEY NOT NULL,
	"xp" integer DEFAULT 0 NOT NULL,
	"xp_spent" integer DEFAULT 0 NOT NULL,
	"level" integer DEFAULT 1 NOT NULL,
	"streak" integer DEFAULT 0 NOT NULL,
	"balance_crc" real DEFAULT 0 NOT NULL,
	"last_seen" timestamp DEFAULT now() NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "privacy_settings" (
	"address" text PRIMARY KEY NOT NULL,
	"hide_pnl" boolean DEFAULT false NOT NULL,
	"hide_total_bet" boolean DEFAULT false NOT NULL,
	"hide_xp_spent" boolean DEFAULT false NOT NULL,
	"hide_game_history" boolean DEFAULT false NOT NULL,
	"hide_from_leaderboard" boolean DEFAULT false NOT NULL,
	"hide_from_search" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "wallet_ledger" (
	"id" serial PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"kind" text NOT NULL,
	"amount_crc" real NOT NULL,
	"balance_after" real NOT NULL,
	"reason" text,
	"tx_hash" text,
	"game_type" text,
	"game_slug" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "wallet_ledger_tx_hash_unique" UNIQUE("tx_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "xp_config" (
	"key" text PRIMARY KEY NOT NULL,
	"value" integer NOT NULL,
	"category" text DEFAULT 'reward' NOT NULL,
	"label" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "blackjack_hands" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'dealing' NOT NULL,
	"outcome" text,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "blackjack_hands_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "blackjack_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#1a5c2e' NOT NULL,
	"accent_color" text DEFAULT '#1a7a3a' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "blackjack_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cashout_tokens" (
	"id" serial PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"amount_crc" real NOT NULL,
	"address" text,
	"status" text DEFAULT 'pending' NOT NULL,
	"proof_tx_hash" text,
	"payout_tx_hash" text,
	"refund_tx_hash" text,
	"error_message" text,
	"debit_ledger_id" text,
	"refund_ledger_id" text,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cashout_tokens_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "coin_flip_results" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"player_choice" text NOT NULL,
	"coin_result" text NOT NULL,
	"outcome" text NOT NULL,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "coin_flip_results_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "coin_flip_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#0EA5E9' NOT NULL,
	"accent_color" text DEFAULT '#0284C7' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "coin_flip_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "crash_dash_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"outcome" text,
	"crash_point" real,
	"cashout_multiplier" real,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "crash_dash_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "crash_dash_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[5,10,50,100]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#16A34A' NOT NULL,
	"accent_color" text DEFAULT '#22C55E' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "crash_dash_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "crc_races_games" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"tier" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"max_players" integer NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"recipient_address" text NOT NULL,
	"is_private" boolean DEFAULT false NOT NULL,
	"players" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" text DEFAULT 'waiting' NOT NULL,
	"game_state" jsonb,
	"winner_address" text,
	"payouts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"rematch_slug" text,
	"started_at" timestamp,
	"finished_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "crc_races_games_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daily_rewards_config" (
	"key" text PRIMARY KEY NOT NULL,
	"rewards" jsonb NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daily_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"address" text,
	"tx_hash" text,
	"date" text NOT NULL,
	"scratch_result" text,
	"scratch_played" boolean DEFAULT false NOT NULL,
	"spin_result" text,
	"spin_played" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "daily_sessions_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "jackpot_pool" (
	"id" serial PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"amount_crc" integer DEFAULT 1 NOT NULL,
	"tx_hash" text NOT NULL,
	"date" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "jackpot_pool_tx_hash_unique" UNIQUE("tx_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dames_games" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"status" text DEFAULT 'waiting_p1' NOT NULL,
	"bet_crc" integer NOT NULL,
	"recipient_address" text NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"player1_address" text,
	"player2_address" text,
	"player1_tx_hash" text,
	"player2_tx_hash" text,
	"player1_token" text,
	"player2_token" text,
	"is_private" boolean DEFAULT false NOT NULL,
	"game_state" jsonb,
	"winner_address" text,
	"rematch_slug" text,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "dames_games_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dice_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"target" real,
	"direction" text,
	"result" real,
	"outcome" text,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "dice_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "dice_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#F59E0B' NOT NULL,
	"accent_color" text DEFAULT '#D97706' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "dice_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hilo_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"outcome" text,
	"streak" integer DEFAULT 0 NOT NULL,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "hilo_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "hilo_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#7C3AED' NOT NULL,
	"accent_color" text DEFAULT '#8B5CF6' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "hilo_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "keno_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"pick_count" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"outcome" text,
	"hits" integer DEFAULT 0 NOT NULL,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "keno_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "keno_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#6366F1' NOT NULL,
	"accent_color" text DEFAULT '#818CF8' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "keno_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lootbox_opens" (
	"id" serial PRIMARY KEY NOT NULL,
	"lootbox_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"player_token" text,
	"reward_crc" real NOT NULL,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"opened_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lootbox_opens_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lootboxes" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"price_per_open_crc" integer DEFAULT 10 NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#92400E' NOT NULL,
	"accent_color" text DEFAULT '#F59E0B' NOT NULL,
	"logo_url" text,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lootboxes_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "draws" (
	"id" serial PRIMARY KEY NOT NULL,
	"lottery_id" integer NOT NULL,
	"winner_address" text NOT NULL,
	"block_number" integer NOT NULL,
	"block_hash" text NOT NULL,
	"participant_count" integer NOT NULL,
	"participant_addresses" text NOT NULL,
	"selection_index" integer NOT NULL,
	"drawn_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "lotteries" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"organizer" text NOT NULL,
	"description" text,
	"ticket_price_crc" integer DEFAULT 5 NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#251B9F' NOT NULL,
	"accent_color" text DEFAULT '#FF491B' NOT NULL,
	"logo_url" text,
	"theme" text DEFAULT 'light' NOT NULL,
	"commission_percent" integer DEFAULT 5 NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "lotteries_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "participants" (
	"id" serial PRIMARY KEY NOT NULL,
	"lottery_id" integer NOT NULL,
	"address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"player_token" text,
	"paid_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "memory_games" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"difficulty" text DEFAULT 'medium' NOT NULL,
	"recipient_address" text NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"player1_address" text,
	"player2_address" text,
	"player1_tx_hash" text,
	"player2_tx_hash" text,
	"player1_token" text,
	"player2_token" text,
	"player1_moves" integer,
	"player1_time" integer,
	"player2_moves" integer,
	"player2_time" integer,
	"is_private" boolean DEFAULT false NOT NULL,
	"rematch_slug" text,
	"grid_seed" text NOT NULL,
	"current_turn" text DEFAULT 'player1' NOT NULL,
	"player1_pairs" integer DEFAULT 0 NOT NULL,
	"player2_pairs" integer DEFAULT 0 NOT NULL,
	"board_state" text DEFAULT '{}' NOT NULL,
	"status" text DEFAULT 'waiting_p1' NOT NULL,
	"winner_address" text,
	"result" text,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "memory_games_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mines_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"mine_count" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"outcome" text,
	"gems_revealed" integer DEFAULT 0 NOT NULL,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "mines_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mines_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"mine_options" jsonb DEFAULT '[1,3,5,10,15,24]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#DC2626' NOT NULL,
	"accent_color" text DEFAULT '#EF4444' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "mines_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "morpion_games" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"recipient_address" text NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"player1_address" text,
	"player2_address" text,
	"player1_tx_hash" text,
	"player2_tx_hash" text,
	"player1_token" text,
	"player2_token" text,
	"is_private" boolean DEFAULT false NOT NULL,
	"board" text DEFAULT '---------' NOT NULL,
	"current_turn" text DEFAULT 'X' NOT NULL,
	"status" text DEFAULT 'waiting_p1' NOT NULL,
	"result" text,
	"winner_address" text,
	"rematch_slug" text,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "morpion_games_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "morpion_moves" (
	"id" serial PRIMARY KEY NOT NULL,
	"game_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"position" integer NOT NULL,
	"symbol" text NOT NULL,
	"move_number" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pfc_games" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"status" text DEFAULT 'waiting_p1' NOT NULL,
	"bet_crc" integer NOT NULL,
	"best_of" integer DEFAULT 3 NOT NULL,
	"recipient_address" text NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"player1_address" text,
	"player2_address" text,
	"player1_tx_hash" text,
	"player2_tx_hash" text,
	"player1_token" text,
	"player2_token" text,
	"is_private" boolean DEFAULT false NOT NULL,
	"game_state" jsonb,
	"winner_address" text,
	"rematch_slug" text,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "pfc_games_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plinko_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"ball_value" real DEFAULT 1 NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"ball_path" jsonb,
	"final_bucket" integer,
	"outcome" text,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "plinko_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plinko_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25,50,100,150]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#7C3AED' NOT NULL,
	"accent_color" text DEFAULT '#8B5CF6' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "plinko_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "relics_games" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"status" text DEFAULT 'waiting_p1' NOT NULL,
	"bet_crc" integer NOT NULL,
	"recipient_address" text NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"player1_address" text,
	"player2_address" text,
	"player1_tx_hash" text,
	"player2_tx_hash" text,
	"player1_token" text,
	"player2_token" text,
	"is_private" boolean DEFAULT false NOT NULL,
	"grid1" jsonb,
	"grid2" jsonb,
	"ready1" integer DEFAULT 0 NOT NULL,
	"ready2" integer DEFAULT 0 NOT NULL,
	"current_turn" text,
	"last_shot" jsonb,
	"winner_address" text,
	"rematch_slug" text,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "relics_games_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "roulette_rounds" (
	"id" serial PRIMARY KEY NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing' NOT NULL,
	"bets" jsonb,
	"result" integer,
	"outcome" text,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending' NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roulette_rounds_transaction_hash_unique" UNIQUE("transaction_hash")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "roulette_tables" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1,5,10,25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#DC2626' NOT NULL,
	"accent_color" text DEFAULT '#B91C1C' NOT NULL,
	"status" text DEFAULT 'active' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roulette_tables_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shop_coupons" (
	"id" serial PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"type" text NOT NULL,
	"used" boolean DEFAULT false NOT NULL,
	"used_at" timestamp,
	"tx_hash_used" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"expires_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shop_items" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text NOT NULL,
	"icon" text NOT NULL,
	"category" text NOT NULL,
	"xp_cost" integer NOT NULL,
	"level_required" integer DEFAULT 1 NOT NULL,
	"refund_type" text,
	"refund_amount_crc" integer,
	"stock" integer,
	"active" boolean DEFAULT true NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "shop_items_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shop_purchases" (
	"id" serial PRIMARY KEY NOT NULL,
	"address" text NOT NULL,
	"item_slug" text NOT NULL,
	"xp_spent" integer NOT NULL,
	"effect_applied" boolean DEFAULT false NOT NULL,
	"expires_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "shop_sessions" (
	"id" serial PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"address" text,
	"tx_hash" text,
	"refunded" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "shop_sessions_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "support_messages" (
	"id" serial PRIMARY KEY NOT NULL,
	"telegram_user_id" bigint NOT NULL,
	"telegram_username" text,
	"telegram_first_name" text,
	"direction" text NOT NULL,
	"text" text NOT NULL,
	"admin_message_id" integer,
	"user_message_id" integer,
	"context" jsonb,
	"wallet_address" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "blackjack_hands" ADD CONSTRAINT "blackjack_hands_table_id_blackjack_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."blackjack_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "coin_flip_results" ADD CONSTRAINT "coin_flip_results_table_id_coin_flip_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."coin_flip_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "crash_dash_rounds" ADD CONSTRAINT "crash_dash_rounds_table_id_crash_dash_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."crash_dash_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "dice_rounds" ADD CONSTRAINT "dice_rounds_table_id_dice_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."dice_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "hilo_rounds" ADD CONSTRAINT "hilo_rounds_table_id_hilo_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."hilo_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "keno_rounds" ADD CONSTRAINT "keno_rounds_table_id_keno_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."keno_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "lootbox_opens" ADD CONSTRAINT "lootbox_opens_lootbox_id_lootboxes_id_fk" FOREIGN KEY ("lootbox_id") REFERENCES "public"."lootboxes"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "draws" ADD CONSTRAINT "draws_lottery_id_lotteries_id_fk" FOREIGN KEY ("lottery_id") REFERENCES "public"."lotteries"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "participants" ADD CONSTRAINT "participants_lottery_id_lotteries_id_fk" FOREIGN KEY ("lottery_id") REFERENCES "public"."lotteries"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "mines_rounds" ADD CONSTRAINT "mines_rounds_table_id_mines_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."mines_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "morpion_moves" ADD CONSTRAINT "morpion_moves_game_id_morpion_games_id_fk" FOREIGN KEY ("game_id") REFERENCES "public"."morpion_games"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "plinko_rounds" ADD CONSTRAINT "plinko_rounds_table_id_plinko_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."plinko_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "roulette_rounds" ADD CONSTRAINT "roulette_rounds_table_id_roulette_tables_id_fk" FOREIGN KEY ("table_id") REFERENCES "public"."roulette_tables"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN null; END $$;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "unique_badge_per_player" ON "player_badges" USING btree ("address","badge_slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cashout_tokens_token_idx" ON "cashout_tokens" USING btree ("token");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cashout_tokens_address_idx" ON "cashout_tokens" USING btree ("address");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "cashout_tokens_status_idx" ON "cashout_tokens" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "unique_address_per_lottery" ON "participants" USING btree ("lottery_id","address");