-- 0011_add_orphan_tables.sql
-- Tables that existed in src/lib/db/schema/* but had no CREATE TABLE in drizzle/.
-- All statements use IF NOT EXISTS so this migration is idempotent:
--   - Neon prod (already has every table) => no-op
--   - fresh local install                 => creates all 16 tables
-- Generated by PR #10 from local DB introspection (+ 2 tables from schema).

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "bot_state" (
	"id" integer DEFAULT 1 NOT NULL,
	"last_nonce" integer NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "bot_state_pkey" PRIMARY KEY("id")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "blackjack_tables" (
	"id" serial NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1, 5, 10, 25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#1a5c2e'::text NOT NULL,
	"accent_color" text DEFAULT '#10B981'::text NOT NULL,
	"status" text DEFAULT 'active'::text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "blackjack_tables_pkey" PRIMARY KEY("id"),
	CONSTRAINT "blackjack_tables_slug_key" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "blackjack_hands" (
	"id" serial NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'dealing'::text NOT NULL,
	"outcome" text,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending'::text NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"player_token" text,
	CONSTRAINT "blackjack_hands_pkey" PRIMARY KEY("id"),
	CONSTRAINT "blackjack_hands_transaction_hash_key" UNIQUE("transaction_hash")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "cashout_tokens" (
	"id" serial NOT NULL,
	"token" text NOT NULL,
	"amount_crc" real NOT NULL,
	"address" text,
	"status" text DEFAULT 'pending'::text NOT NULL,
	"proof_tx_hash" text,
	"payout_tx_hash" text,
	"refund_tx_hash" text,
	"error_message" text,
	"debit_ledger_id" text,
	"refund_ledger_id" text,
	"expires_at" timestamp NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "cashout_tokens_pkey" PRIMARY KEY("id"),
	CONSTRAINT "cashout_tokens_token_key" UNIQUE("token")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "coin_flip_tables" (
	"id" serial NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1, 5, 10, 25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#0EA5E9'::text NOT NULL,
	"accent_color" text DEFAULT '#0284C7'::text NOT NULL,
	"status" text DEFAULT 'active'::text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "coin_flip_tables_pkey" PRIMARY KEY("id"),
	CONSTRAINT "coin_flip_tables_slug_key" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "coin_flip_results" (
	"id" serial NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"player_choice" text NOT NULL,
	"coin_result" text NOT NULL,
	"outcome" text NOT NULL,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending'::text NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "coin_flip_results_pkey" PRIMARY KEY("id"),
	CONSTRAINT "coin_flip_results_transaction_hash_key" UNIQUE("transaction_hash")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "crc_races_games" (
	"id" serial NOT NULL,
	"slug" text NOT NULL,
	"tier" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"max_players" integer NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"recipient_address" text NOT NULL,
	"is_private" boolean DEFAULT false NOT NULL,
	"players" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" text DEFAULT 'waiting'::text NOT NULL,
	"game_state" jsonb,
	"winner_address" text,
	"payouts" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"payout_status" text DEFAULT 'pending'::text NOT NULL,
	"rematch_slug" text,
	"started_at" timestamp,
	"finished_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "crc_races_games_pkey" PRIMARY KEY("id"),
	CONSTRAINT "crc_races_games_slug_key" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "feature_flags" (
	"key" text NOT NULL,
	"label" text NOT NULL,
	"category" text DEFAULT 'general'::text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"status" text DEFAULT 'enabled'::text NOT NULL,
	CONSTRAINT "feature_flags_pkey" PRIMARY KEY("key")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "pfc_games" (
	"id" serial NOT NULL,
	"slug" text NOT NULL,
	"status" text DEFAULT 'waiting_p1'::text NOT NULL,
	"bet_crc" integer NOT NULL,
	"best_of" integer DEFAULT 3 NOT NULL,
	"recipient_address" text NOT NULL,
	"commission_pct" integer DEFAULT 5 NOT NULL,
	"player1_address" text,
	"player2_address" text,
	"player1_tx_hash" text,
	"player2_tx_hash" text,
	"player1_token" text,
	"player2_token" text,
	"is_private" boolean DEFAULT false NOT NULL,
	"game_state" jsonb,
	"winner_address" text,
	"payout_status" text DEFAULT 'pending'::text NOT NULL,
	"payout_tx_hash" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"rematch_slug" text,
	CONSTRAINT "pfc_games_pkey" PRIMARY KEY("id"),
	CONSTRAINT "pfc_games_slug_key" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plinko_tables" (
	"id" serial NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1, 5, 10, 25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#7C3AED'::text NOT NULL,
	"accent_color" text DEFAULT '#8B5CF6'::text NOT NULL,
	"status" text DEFAULT 'active'::text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "plinko_tables_pkey" PRIMARY KEY("id"),
	CONSTRAINT "plinko_tables_slug_key" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plinko_rounds" (
	"id" serial NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing'::text NOT NULL,
	"ball_path" jsonb,
	"final_bucket" integer,
	"outcome" text,
	"final_multiplier" real,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending'::text NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"ball_value" real DEFAULT 1 NOT NULL,
	CONSTRAINT "plinko_rounds_pkey" PRIMARY KEY("id"),
	CONSTRAINT "plinko_rounds_transaction_hash_key" UNIQUE("transaction_hash")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "roulette_tables" (
	"id" serial NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"bet_options" jsonb DEFAULT '[1, 5, 10, 25]'::jsonb NOT NULL,
	"recipient_address" text NOT NULL,
	"primary_color" text DEFAULT '#DC2626'::text NOT NULL,
	"accent_color" text DEFAULT '#B91C1C'::text NOT NULL,
	"status" text DEFAULT 'active'::text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roulette_tables_pkey" PRIMARY KEY("id"),
	CONSTRAINT "roulette_tables_slug_key" UNIQUE("slug")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "roulette_rounds" (
	"id" serial NOT NULL,
	"table_id" integer NOT NULL,
	"player_address" text NOT NULL,
	"transaction_hash" text NOT NULL,
	"bet_crc" integer NOT NULL,
	"player_token" text,
	"game_state" jsonb NOT NULL,
	"status" text DEFAULT 'playing'::text NOT NULL,
	"bets" jsonb,
	"result" integer,
	"outcome" text,
	"payout_crc" real,
	"payout_status" text DEFAULT 'pending'::text NOT NULL,
	"payout_tx_hash" text,
	"error_message" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roulette_rounds_pkey" PRIMARY KEY("id"),
	CONSTRAINT "roulette_rounds_transaction_hash_key" UNIQUE("transaction_hash")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "support_messages" (
	"id" serial NOT NULL,
	"telegram_user_id" bigint NOT NULL,
	"telegram_username" text,
	"telegram_first_name" text,
	"direction" text NOT NULL,
	"text" text NOT NULL,
	"admin_message_id" integer,
	"user_message_id" integer,
	"context" jsonb,
	"wallet_address" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "support_messages_pkey" PRIMARY KEY("id")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "xp_config" (
	"key" text NOT NULL,
	"value" integer NOT NULL,
	"category" text DEFAULT 'reward' NOT NULL,
	"label" text NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "xp_config_pkey" PRIMARY KEY("key")
);

--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "daily_rewards_config" (
	"key" text NOT NULL,
	"rewards" jsonb NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "daily_rewards_config_pkey" PRIMARY KEY("key")
);

